//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFPCharting {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NFPCharting.AppResources.es", typeof(AppResources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MenstrualLabel {
            get {
                return ResourceManager.GetString("MenstrualLabel", resourceCulture);
            }
        }
        
        internal static string IndicatorLabel {
            get {
                return ResourceManager.GetString("IndicatorLabel", resourceCulture);
            }
        }
        
        internal static string ColorLabel {
            get {
                return ResourceManager.GetString("ColorLabel", resourceCulture);
            }
        }
        
        internal static string SensationLabel {
            get {
                return ResourceManager.GetString("SensationLabel", resourceCulture);
            }
        }
        
        internal static string FrequencyLabel {
            get {
                return ResourceManager.GetString("FrequencyLabel", resourceCulture);
            }
        }
        
        internal static string PeakLabel {
            get {
                return ResourceManager.GetString("PeakLabel", resourceCulture);
            }
        }
        
        internal static string DayCountLabel {
            get {
                return ResourceManager.GetString("DayCountLabel", resourceCulture);
            }
        }
        
        internal static string IntercourseLabel {
            get {
                return ResourceManager.GetString("IntercourseLabel", resourceCulture);
            }
        }
        
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        internal static string UpdateLabel {
            get {
                return ResourceManager.GetString("UpdateLabel", resourceCulture);
            }
        }
        
        internal static string ShowLabel {
            get {
                return ResourceManager.GetString("ShowLabel", resourceCulture);
            }
        }
        
        internal static string SendLabel {
            get {
                return ResourceManager.GetString("SendLabel", resourceCulture);
            }
        }
        
        internal static string StampLabel {
            get {
                return ResourceManager.GetString("StampLabel", resourceCulture);
            }
        }
        
        internal static string EditDayLabel {
            get {
                return ResourceManager.GetString("EditDayLabel", resourceCulture);
            }
        }
        
        internal static string EditCyclesLabel {
            get {
                return ResourceManager.GetString("EditCyclesLabel", resourceCulture);
            }
        }
        
        internal static string ViewCyclesLabel {
            get {
                return ResourceManager.GetString("ViewCyclesLabel", resourceCulture);
            }
        }
        
        internal static string ViewingCyclesLabel {
            get {
                return ResourceManager.GetString("ViewingCyclesLabel", resourceCulture);
            }
        }
        
        internal static string CyclesLabel {
            get {
                return ResourceManager.GetString("CyclesLabel", resourceCulture);
            }
        }
        
        internal static string CyclesToDisplayLabel {
            get {
                return ResourceManager.GetString("CyclesToDisplayLabel", resourceCulture);
            }
        }
        
        internal static string AddNewCycleLabel {
            get {
                return ResourceManager.GetString("AddNewCycleLabel", resourceCulture);
            }
        }
        
        internal static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        internal static string StartingDateLabel {
            get {
                return ResourceManager.GetString("StartingDateLabel", resourceCulture);
            }
        }
        
        internal static string CycleStartDateLabel {
            get {
                return ResourceManager.GetString("CycleStartDateLabel", resourceCulture);
            }
        }
        
        internal static string CurrentCycleLabel {
            get {
                return ResourceManager.GetString("CurrentCycleLabel", resourceCulture);
            }
        }
        
        internal static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
        
        internal static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        internal static string CycleIDLabel {
            get {
                return ResourceManager.GetString("CycleIDLabel", resourceCulture);
            }
        }
        
        internal static string DatabaseUpdateLabel {
            get {
                return ResourceManager.GetString("DatabaseUpdateLabel", resourceCulture);
            }
        }
        
        internal static string AlertLabel {
            get {
                return ResourceManager.GetString("AlertLabel", resourceCulture);
            }
        }
        
        internal static string UpdateErrorLabel {
            get {
                return ResourceManager.GetString("UpdateErrorLabel", resourceCulture);
            }
        }
        
        internal static string UpdateSuccessLabel {
            get {
                return ResourceManager.GetString("UpdateSuccessLabel", resourceCulture);
            }
        }
        
        internal static string OKLabel {
            get {
                return ResourceManager.GetString("OKLabel", resourceCulture);
            }
        }
        
        internal static string AddCycleSuccessLabel {
            get {
                return ResourceManager.GetString("AddCycleSuccessLabel", resourceCulture);
            }
        }
        
        internal static string AddCycleErrorLabel {
            get {
                return ResourceManager.GetString("AddCycleErrorLabel", resourceCulture);
            }
        }
        
        internal static string SendErrorLabel {
            get {
                return ResourceManager.GetString("SendErrorLabel", resourceCulture);
            }
        }
        
        internal static string DeleteErrorLabel {
            get {
                return ResourceManager.GetString("DeleteErrorLabel", resourceCulture);
            }
        }
        
        internal static string DeleteSuccessLabel {
            get {
                return ResourceManager.GetString("DeleteSuccessLabel", resourceCulture);
            }
        }
        
        internal static string AddCycleButtonLabel {
            get {
                return ResourceManager.GetString("AddCycleButtonLabel", resourceCulture);
            }
        }
        
        internal static string EmailSubjectLabel {
            get {
                return ResourceManager.GetString("EmailSubjectLabel", resourceCulture);
            }
        }
        
        internal static string EmailBodyLabel {
            get {
                return ResourceManager.GetString("EmailBodyLabel", resourceCulture);
            }
        }
        
        internal static string ImportExportLabel {
            get {
                return ResourceManager.GetString("ImportExportLabel", resourceCulture);
            }
        }
        
        internal static string ImportLabel {
            get {
                return ResourceManager.GetString("ImportLabel", resourceCulture);
            }
        }
        
        internal static string ExportLabel {
            get {
                return ResourceManager.GetString("ExportLabel", resourceCulture);
            }
        }
        
        internal static string ExportSubjectLabel {
            get {
                return ResourceManager.GetString("ExportSubjectLabel", resourceCulture);
            }
        }
        
        internal static string ExportBodyLabel {
            get {
                return ResourceManager.GetString("ExportBodyLabel", resourceCulture);
            }
        }
        
        internal static string ImportErrorLabel {
            get {
                return ResourceManager.GetString("ImportErrorLabel", resourceCulture);
            }
        }
        
        internal static string ImportNote {
            get {
                return ResourceManager.GetString("ImportNote", resourceCulture);
            }
        }
        
        internal static string ImportErrorPermissionsAndroid {
            get {
                return ResourceManager.GetString("ImportErrorPermissionsAndroid", resourceCulture);
            }
        }
        
        internal static string ImportErrorPermissionsApple {
            get {
                return ResourceManager.GetString("ImportErrorPermissionsApple", resourceCulture);
            }
        }
    }
}
