//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFPCharting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NFPCharting.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Cycle using &quot;+&quot; button..
        /// </summary>
        internal static string AddCycleButtonLabel {
            get {
                return ResourceManager.GetString("AddCycleButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add new cycle, starting date already exists..
        /// </summary>
        internal static string AddCycleErrorLabel {
            get {
                return ResourceManager.GetString("AddCycleErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New cycle has been added..
        /// </summary>
        internal static string AddCycleSuccessLabel {
            get {
                return ResourceManager.GetString("AddCycleSuccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Cycle.
        /// </summary>
        internal static string AddNewCycleLabel {
            get {
                return ResourceManager.GetString("AddNewCycleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string AlertLabel {
            get {
                return ResourceManager.GetString("AlertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B - Brown (or black).
        /// </summary>
        internal static string BColor {
            get {
                return ResourceManager.GetString("BColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B - Brown (or black).
        /// </summary>
        internal static string BMenstrual {
            get {
                return ResourceManager.GetString("BMenstrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C - Cloudy (white).
        /// </summary>
        internal static string CColor {
            get {
                return ResourceManager.GetString("CColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK - Cloudy/Clear.
        /// </summary>
        internal static string CKColor {
            get {
                return ResourceManager.GetString("CKColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        internal static string ColorLabel {
            get {
                return ResourceManager.GetString("ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Cycle?: .
        /// </summary>
        internal static string CurrentCycleLabel {
            get {
                return ResourceManager.GetString("CurrentCycleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current number of days:.
        /// </summary>
        internal static string CurrNumLabel {
            get {
                return ResourceManager.GetString("CurrNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycleID: .
        /// </summary>
        internal static string CycleIDLabel {
            get {
                return ResourceManager.GetString("CycleIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error modifying cycle..
        /// </summary>
        internal static string CycleModErrorLabel {
            get {
                return ResourceManager.GetString("CycleModErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Modified..
        /// </summary>
        internal static string CycleModifiedLabel {
            get {
                return ResourceManager.GetString("CycleModifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles.
        /// </summary>
        internal static string CyclesLabel {
            get {
                return ResourceManager.GetString("CyclesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Start Date: .
        /// </summary>
        internal static string CycleStartDateLabel {
            get {
                return ResourceManager.GetString("CycleStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles to Display:.
        /// </summary>
        internal static string CyclesToDisplayLabel {
            get {
                return ResourceManager.GetString("CyclesToDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Update.
        /// </summary>
        internal static string DatabaseUpdateLabel {
            get {
                return ResourceManager.GetString("DatabaseUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Count:.
        /// </summary>
        internal static string DayCountLabel {
            get {
                return ResourceManager.GetString("DayCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting cycle..
        /// </summary>
        internal static string DeleteErrorLabel {
            get {
                return ResourceManager.GetString("DeleteErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this cycle?.
        /// </summary>
        internal static string DeletePrompt {
            get {
                return ResourceManager.GetString("DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        internal static string DeleteQLabel {
            get {
                return ResourceManager.GetString("DeleteQLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle and data deleted..
        /// </summary>
        internal static string DeleteSuccessLabel {
            get {
                return ResourceManager.GetString("DeleteSuccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cycles.
        /// </summary>
        internal static string EditCyclesLabel {
            get {
                return ResourceManager.GetString("EditCyclesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Day.
        /// </summary>
        internal static string EditDayLabel {
            get {
                return ResourceManager.GetString("EditDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 - Tacky (1/2&quot;-3/4&quot;).
        /// </summary>
        internal static string EightIndicator {
            get {
                return ResourceManager.GetString("EightIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending NFP Chart.
        /// </summary>
        internal static string EmailBodyLabel {
            get {
                return ResourceManager.GetString("EmailBodyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFP Chart.
        /// </summary>
        internal static string EmailSubjectLabel {
            get {
                return ResourceManager.GetString("EmailSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending NFP Database.
        /// </summary>
        internal static string ExportBodyLabel {
            get {
                return ResourceManager.GetString("ExportBodyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportLabel {
            get {
                return ResourceManager.GetString("ExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFP Database Export.
        /// </summary>
        internal static string ExportSubjectLabel {
            get {
                return ResourceManager.GetString("ExportSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Shiny w/o lubrication.
        /// </summary>
        internal static string FourIndicator {
            get {
                return ResourceManager.GetString("FourIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency:.
        /// </summary>
        internal static string FrequencyLabel {
            get {
                return ResourceManager.GetString("FrequencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G - Gummy.
        /// </summary>
        internal static string GColor {
            get {
                return ResourceManager.GetString("GColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G - Gummy.
        /// </summary>
        internal static string GSensation {
            get {
                return ResourceManager.GetString("GSensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H - Heavy flow.
        /// </summary>
        internal static string HMenstrual {
            get {
                return ResourceManager.GetString("HMenstrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing database. Selected file was not an NFP Database file..
        /// </summary>
        internal static string ImportErrorDBLabel {
            get {
                return ResourceManager.GetString("ImportErrorDBLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Importing Database.
        /// </summary>
        internal static string ImportErrorLabel {
            get {
                return ResourceManager.GetString("ImportErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enable the storage permission to use this feature. Toggle: Settings&gt;Apps&gt;NFP Charting&gt;Permissions&gt;Storage.
        /// </summary>
        internal static string ImportErrorPermissionsAndroid {
            get {
                return ResourceManager.GetString("ImportErrorPermissionsAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enable iCloud to use this feature..
        /// </summary>
        internal static string ImportErrorPermissionsApple {
            get {
                return ResourceManager.GetString("ImportErrorPermissionsApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string ImportExportBaseLabel {
            get {
                return ResourceManager.GetString("ImportExportBaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Backup.
        /// </summary>
        internal static string ImportExportLabel {
            get {
                return ResourceManager.GetString("ImportExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is used for backing up your data.
        ///
        ///Use the &quot;Import&quot; button to load a previously saved database (.db) file.
        ///
        ///Use the &quot;Export&quot; button to save the current database file or share with another person using this app.  
        ///
        ///NOTE: The file that is exported/saved using this function is a raw data file and not a user viewable file..
        /// </summary>
        internal static string ImportExportOptions {
            get {
                return ResourceManager.GetString("ImportExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportLabel {
            get {
                return ResourceManager.GetString("ImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must close the app and restart it for the changes to take effect..
        /// </summary>
        internal static string ImportNote {
            get {
                return ResourceManager.GetString("ImportNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator:.
        /// </summary>
        internal static string IndicatorLabel {
            get {
                return ResourceManager.GetString("IndicatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercourse:.
        /// </summary>
        internal static string IntercourseLabel {
            get {
                return ResourceManager.GetString("IntercourseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K - Clear.
        /// </summary>
        internal static string KColor {
            get {
                return ResourceManager.GetString("KColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L - Light flow.
        /// </summary>
        internal static string LMenstrual {
            get {
                return ResourceManager.GetString("LMenstrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L - Lubricative.
        /// </summary>
        internal static string LSensation {
            get {
                return ResourceManager.GetString("LSensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menstrual:.
        /// </summary>
        internal static string MenstrualLabel {
            get {
                return ResourceManager.GetString("MenstrualLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - Moderate flow.
        /// </summary>
        internal static string MMenstrual {
            get {
                return ResourceManager.GetString("MMenstrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Cycle.
        /// </summary>
        internal static string ModCycleLabel {
            get {
                return ResourceManager.GetString("ModCycleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string ModifyLabel {
            get {
                return ResourceManager.GetString("ModifyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: If the new number of days is shorter, any stored data for the removed days will be permanently deleted..
        /// </summary>
        internal static string ModNoteLabel {
            get {
                return ResourceManager.GetString("ModNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NALabel {
            get {
                return ResourceManager.GetString("NALabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New number of days:.
        /// </summary>
        internal static string NewNumLabel {
            get {
                return ResourceManager.GetString("NewNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Days in Cycle:.
        /// </summary>
        internal static string NumDaysLabel {
            get {
                return ResourceManager.GetString("NumDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKLabel {
            get {
                return ResourceManager.GetString("OKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P - Pasty.
        /// </summary>
        internal static string PColor {
            get {
                return ResourceManager.GetString("PColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak:.
        /// </summary>
        internal static string PeakLabel {
            get {
                return ResourceManager.GetString("PeakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P - Pasty.
        /// </summary>
        internal static string PSensation {
            get {
                return ResourceManager.GetString("PSensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending email. You must have a mail account setup to use this feature..
        /// </summary>
        internal static string SendErrorLabel {
            get {
                return ResourceManager.GetString("SendErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string SendLabel {
            get {
                return ResourceManager.GetString("SendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensation:.
        /// </summary>
        internal static string SensationLabel {
            get {
                return ResourceManager.GetString("SensationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ShowLabel {
            get {
                return ResourceManager.GetString("ShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Sticky (1/4&quot;).
        /// </summary>
        internal static string SixIndicator {
            get {
                return ResourceManager.GetString("SixIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp.
        /// </summary>
        internal static string StampLabel {
            get {
                return ResourceManager.GetString("StampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date:.
        /// </summary>
        internal static string StartingDateLabel {
            get {
                return ResourceManager.GetString("StartingDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10DL - Damp w/ lubrication.
        /// </summary>
        internal static string TenDLIndicator {
            get {
                return ResourceManager.GetString("TenDLIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 - Stretchy (1&quot;+).
        /// </summary>
        internal static string TenIndicator {
            get {
                return ResourceManager.GetString("TenIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10SL - Shiny w/ lubrication.
        /// </summary>
        internal static string TenSLIndicator {
            get {
                return ResourceManager.GetString("TenSLIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10WL - Wet w/ lubrication.
        /// </summary>
        internal static string TenWLIndicator {
            get {
                return ResourceManager.GetString("TenWLIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days must be 1 or more..
        /// </summary>
        internal static string TooFewDaysLabel {
            get {
                return ResourceManager.GetString("TooFewDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days must be 365 or less..
        /// </summary>
        internal static string TooManyDaysLabel {
            get {
                return ResourceManager.GetString("TooManyDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Damp w/o lubrication.
        /// </summary>
        internal static string TwoIndicator {
            get {
                return ResourceManager.GetString("TwoIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2W - Wet w/o lubrication.
        /// </summary>
        internal static string TwoWIndicator {
            get {
                return ResourceManager.GetString("TwoWIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating data. Did you forget to add a cycle?.
        /// </summary>
        internal static string UpdateErrorLabel {
            get {
                return ResourceManager.GetString("UpdateErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateLabel {
            get {
                return ResourceManager.GetString("UpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle data has been updated..
        /// </summary>
        internal static string UpdateSuccessLabel {
            get {
                return ResourceManager.GetString("UpdateSuccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Share.
        /// </summary>
        internal static string ViewCyclesLabel {
            get {
                return ResourceManager.GetString("ViewCyclesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Share Cycles.
        /// </summary>
        internal static string ViewingCyclesLabel {
            get {
                return ResourceManager.GetString("ViewingCyclesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is used for viewing and sharing your chart.
        ///
        ///Use the &quot;View&quot; button to view your chart on your device in this app.
        ///
        ///Use the &quot;Share&quot; button to send the chart to yourself or another person as an HTML file, which can be viewed or printed from a web browser..
        /// </summary>
        internal static string ViewOptions {
            get {
                return ResourceManager.GetString("ViewOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VL - Very light flow.
        /// </summary>
        internal static string VLMenstrual {
            get {
                return ResourceManager.GetString("VLMenstrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y - Yellow.
        /// </summary>
        internal static string YColor {
            get {
                return ResourceManager.GetString("YColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - Dry.
        /// </summary>
        internal static string ZeroIndicator {
            get {
                return ResourceManager.GetString("ZeroIndicator", resourceCulture);
            }
        }
    }
}
